title: Agile Open Northwest
email: info@agileopennorthwest.com
#next-other-event-url: /openAgileManagement
#next-other-event-fullname: "Open Agile Management"
#next-other-event-shortname: "Open Agile Management"
last-other-event-url: /openAgileManagement
last-other-event-fullname: "Open Agile Management"
last-other-event-shortname: "Open Agile Management"
years:
- 2020
- 2019
- 2018
- 2017
- 2016
- 2015
- 2014

hosts:
- name: Aki Namioka
  img: aki.png
  bio: |
    Aki has been an Agile practitioner since 2002 and a Certified Scrum Master since 2010. She specializes in Agile coaching, and has helped several organizations transform into high-functioning Agile teams, using XP, Scrum, and Kanban. Aki's background includes Boeing, IBM Global Services, and Cisco Systems. Aki enjoys learning from others in the Agile community, and is active in BeyondAgile and Agile Open Northwest.
- name: Ian Savage
  img: ian.png
  bio: |
    A quality evangelist, Ian Savage is a veteran software developer, quality engineer, and manager with experience in manufacturing, financial services, construction project estimating, and software security. For more than thirty years, he has worked to improve productivity and software quality through rigorous development methods and processes and now through the pragmatic application of agile methods.

    He founded/co-founded various Pacific Northwest software and quality volunteer organizations. By day he works with the Quality Initiatives Team at McAfee focusing on metrics, static analysis, and quality systems.  His present interests are software security, insourcing vs. outsourcing, and quality training. Like many others, Ian looks forward to retirement or Career 2.0.
- name: Jeremy Lightsmith
  img: jeremy.jpg
  bio: |
    Jeremy Lightsmith spends most of his time and energy building highly performant software development teams.

    A seasoned agile coach, trainer, and facilitator, Jeremy excels at creating environments where teams can discover how they work best. He has a deep understanding of agile, and is constantly looking for better ways to share knowledge and collaborate. As a presenter, Jeremy favors interactive and group techniques and pulls from disciplines as diverse as Theatre Improv and Montessori.

    Find Jeremy at [http://jeremylightsmith.com](http://jeremylightsmith.com) or [@lightsmith](http://twitter.com/lightsmith).
- name: Michael J. Tardiff
  img: michael.jpg
  bio: |
    I love hearing what people want to do and helping them see the ways in which they might do it. In doing  the work, we discover the work that needs to be done.

    For the last decade that’s been my story: facilitator, trainer, coach, mentor, guide, storyteller, provocateur. Happiness for me is working with a team of people who are different from me; together, we serve others better than I could alone. Along the way, I've held all the software roles that begin with "p" and end with "manager." Twice I was a director at a growing startup. My early years were spent technically writing.

    I write things at [FeelingAgile.com](http://feelingagile.com). Still available on iTunes is the “The Agile Coach” podcast. @mjt on Twitter is me being short. Invite me and I'll talk, wherever and whenever you like. Agile Open Northwest’s annual Open Space brings me joy. And I find peace sailing the waters north of Seattle.
- name: Nora Beyerle
  img: nora.jpeg
  bio: |
    I journeyed into technology via a music education. Working in the software industry since 2000, I’ve explored responsibilities of business analysis, project management, and people management. It was the agile values and principles that resonated strongest with me, and I have since focused on coaching agile development teams and championing individuals. I appreciate all the learning opportunities within our agile community of practice! I enjoy volunteering at AgilePDX, and now joining Agile Open Northwest. Additionally I am looking forward to further collaborate with Future of Work communities. I believe that people can change the world, and that we can achieve this by being curious, open, and kind.

    I hesitantly tweet at @sunhiltb.
- name: Troy Frever
  img: troy.jpg
  bio: |
    Troy Frever discovered XP in 2000, after two decades as a professional software developer. Since then he has been an Extreme Programmer and Coach for a number of companies in the Seattle area, including Smilebox, Aviarc, RealNetworks, and many more. He was recenlty co-founder and CTO of Blok24, and is currently having a grand time as VP of Engineering at LiquidPlanner. When he's not writing unit tests or refactoring mercilessly, Troy enjoys backpacking and skiing with his family and playing Ultimate Frisbee. Troy is also a former organizer of the Seattle Extreme Programming Users Group (SXPUG) and a co-founder of Seattle's Beyond Agile user group.


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# social:
#   - title: twitter
#     url: http://twitter.com/jekyllrb
#   - title: facebook
#     url:
#   - title: stack-overflow
#     url: http://stackoverflow.com/questions/tagged/jekyll
#   - title: bitbucket 
#     url: http://bitbucket.org/jekyll
#   - title: github
#     url: http://github.com/jekyll

# Build settings
markdown: kramdown
permalink: pretty

exclude: [bin, less, Gemfile, Gemfile.lock, makefile, README.md]